### ISSUE TITLE
crash occured (I was a little overzealous plucking stars from the sky)

### ISSUE THREAD

**Issue by Yay4** [sleepingdragoninn/starcaller#1]
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at folk.sisby.starcaller.item.StardustItem.method_54465(StardustItem.java:103)
	at net.minecraft.class_1799.method_7982(class_1799.java:524)
	at net.minecraft.class_1734.method_7669(class_1734.java:47)
	at net.minecraft.class_1734.method_7667(class_1734.java:57)
	at net.minecraft.class_1703.method_34249(class_1703.java:421)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1703.method_30010(class_1703.java:419)
	at net.minecraft.class_1703.method_7593(class_1703.java:294)
	at net.minecraft.class_636.method_2906(class_636.java:448)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_479.method_2383(class_479.java:101)
	at net.minecraft.class_465.method_25402(class_465.java:349)
	at net.minecraft.class_479.method_25402(class_479.java:90)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220)

also dropping the stardust didn't seem to put the star back in the sky but wierdly duped it

**Comment by sleepingdragoninn** [comment]
should be solved in 0.4!

**Comment by Yay4** [comment]
thanks!
